In [3]:
import os
import pandas as pd
import re

# Full results lassoCV

In [2]:
def read_results(res_dir_path, model_name):
    res = pd.DataFrame()
    for file in os.listdir(res_dir_path):
        if file.endswith('.csv'):
            dataset = file.split('.')[0]
            df = pd.read_csv(os.path.join(res_dir_path, file), index_col=0)
            df['Dataset'] = dataset
            res = pd.concat([res, df], ignore_index=True)
    res['Model'] = model_name
    return res

In [3]:
prot_lengths = {}

# viral proteins
for prot in os.listdir('../data/viral/metadata/'):
    if prot.endswith('.csv'):
        df = pd.read_csv(os.path.join('../data/viral/metadata/', prot), index_col=0)
        prot_lengths[prot.split('.csv')[0]] = int(df['sequence'].apply(lambda x: len(x)).mean())

# non-viral proteins
for prot in os.listdir('../data/cellular/metadata/'):
    if prot.endswith('.csv'):
        df = pd.read_csv(os.path.join('../data/cellular/metadata/', prot), index_col=0)
        prot_lengths[prot.split('.csv')[0]] = int(df['sequence'].apply(lambda x: len(x)).mean())

In [6]:
res_full = pd.DataFrame() 
for model in ['esm2_650M', 'esmc_600M', 'esm2_3B_Sawhney', 'esm2_650M_CRVDB', 'esm2_650M_URVDB']:
    for source in ['viral', 'cellular']:
        for method in ['pool_split', 'site_split']:
            res_dir_path = f'../experiments/lassoCV/{model}/{source}/{method}/'
            res = read_results(res_dir_path, model)
            res['Source'] = source
            res['Split'] = method
            res_full = pd.concat([res_full, res], ignore_index=True)

rename_map = {
    'esm2_650M':'ESM-2 650M',
    'esmc_600M':'ESM C 600M',
    'esm2_650M_CRVDB':'ESM-2-CRVDB', 
    'esm2_650M_URVDB':'ESM-2-URVDB', 
    'esm2_3B_Sawhney':'ESM-2 3B Sawhney',
    'pool_split':'Pooled Split',
    'site_split':'Stratified Site Split',
    }

res_full.replace(rename_map, inplace=True)
res_full['prot_length'] = res_full['Dataset'].map(prot_lengths)
res_full

,Fold,R2_score_train,MAE_score_train,RMSE_score_train,R2_score_test,MAE_score_test,RMSE_score_test,rho_score_train,rho_score_test,num_nonzero_coefs,Dataset,Model,Source,Split,prot_length
0,1,0.498480,0.580306,0.708872,0.358182,0.654775,0.797435,0.701069,0.592824,744,LASSA_GP_Carr,ESM-2 650M,viral,Pooled Split,491
1,2,0.498539,0.576693,0.706440,0.388061,0.635983,0.789648,0.698486,0.629849,830,LASSA_GP_Carr,ESM-2 650M,viral,Pooled Split,491
2,3,0.498067,0.580833,0.710069,0.359596,0.640366,0.792939,0.700305,0.607418,837,LASSA_GP_Carr,ESM-2 650M,viral,Pooled Split,491
3,4,0.506127,0.571101,0.699868,0.365190,0.661099,0.809581,0.704549,0.603481,825,LASSA_GP_Carr,ESM-2 650M,viral,Pooled Split,491
4,5,0.498049,0.577764,0.707999,0.370940,0.643226,0.794802,0.696111,0.628901,789,LASSA_GP_Carr,ESM-2 650M,viral,Pooled Split,491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3695,1,0.556777,0.530624,0.640649,0.271254,0.828748,0.962328,0.753329,0.528852,60,TIM_THETH,ESM-2-URVDB,cellular,Stratified Site Split,254
3696,2,0.545617,0.558412,0.673132,0.182650,0.779220,0.906562,0.746372,0.443394,63,TIM_THETH,ESM-2-URVDB,cellular,Stratified Site Split,254
3697,3,0.570453,0.549776,0.669046,0.285414,0.649461,0.769758,0.759813,0.547891,76,TIM_THETH,ESM-2-URVDB,cellular,Stratified Site Split,254
3698,4,0.568428,0.538320,0.656225,0.226402,0.747678,0.878068,0.759005,0.461288,77,TIM_THETH,ESM-2-URVDB,cellular,Stratified Site Split,254
3699,5,0.312849,0.732727,0.838031,-0.009321,0.821172,0.950249,0.580703,0.220518,13,TIM_THETH,ESM-2-URVDB,cellular,Stratified Site Split,254

In [8]:
res_full.to_csv('../experiments/lassoCV/res_full_lassoCV.csv')

# AVG (site-means) results

In [8]:
def read_results(res_dir_path, model_name):
    res = pd.DataFrame()
    for file in os.listdir(res_dir_path):
        if file.endswith('.csv'):
            dataset = file.split('.')[0]
            df = pd.read_csv(os.path.join(res_dir_path, file), index_col=0)
            df['Dataset'] = dataset
            res = pd.concat([res, df], ignore_index=True)
    res['Model'] = model_name
    return res

In [5]:
prot_lengths = {}

# viral proteins
for prot in os.listdir('../data/viral/metadata/'):
    if prot.endswith('.csv'):
        df = pd.read_csv(os.path.join('../data/viral/metadata/', prot), index_col=0)
        prot_lengths[prot.split('.csv')[0]] = int(df['sequence'].apply(lambda x: len(x)).mean())

# non-viral proteins
for prot in os.listdir('../data/cellular/metadata/'):
    if prot.endswith('.csv'):
        df = pd.read_csv(os.path.join('../data/cellular/metadata/', prot), index_col=0)
        prot_lengths[prot.split('.csv')[0]] = int(df['sequence'].apply(lambda x: len(x)).mean())

In [6]:
AVG = pd.DataFrame()
for model in ['AVG']:
    for source in ['viral', 'cellular']:
        for method in ['pool_split']:
            res_dir_path = f'../experiments/{model}/{source}/{method}/'
            res = read_results(res_dir_path, model)
            res['Source'] = source
            res['Split'] = method
            AVG = pd.concat([AVG, res], ignore_index=True)

AVG = AVG.replace("pool_split", "Pooled Split")
AVG

,Model,Fold,R2_score_train,MAE_score_train,RMSE_score_train,R2_score_test,MAE_score_test,RMSE_score_test,rho_score_train,rho_score_test,Dataset,Source,Split
0,AVG,1,0.530925,0.511884,0.683361,0.424830,0.567484,0.765066,0.734405,0.669716,SARS2_PLPRO_abundance_Wu,viral,Pooled Split
1,AVG,2,0.521827,0.515027,0.691632,0.461210,0.551556,0.732446,0.731561,0.683581,SARS2_PLPRO_abundance_Wu,viral,Pooled Split
2,AVG,3,0.527835,0.510688,0.683042,0.433635,0.573968,0.768914,0.733999,0.671194,SARS2_PLPRO_abundance_Wu,viral,Pooled Split
3,AVG,1,0.632854,0.422123,0.603981,0.673508,0.412015,0.578420,0.761273,0.792606,LAMBDA_HCP_Tsuboyama,viral,Pooled Split
4,AVG,2,0.625207,0.427129,0.611822,0.692847,0.410369,0.553779,0.770798,0.752323,LAMBDA_HCP_Tsuboyama,viral,Pooled Split
...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,AVG,2,0.263463,0.624286,0.853615,0.186157,0.681182,0.921145,0.471661,0.364794,B3VI55_LIPST_Whitehead2015,cellular,Pooled Split
218,AVG,3,0.275332,0.623867,0.845470,0.143653,0.690232,0.950018,0.473400,0.347827,B3VI55_LIPST_Whitehead2015,cellular,Pooled Split
219,AVG,1,0.549891,0.462756,0.676457,0.498551,0.507987,0.684111,0.740102,0.694642,RASH_HUMAN_Kuriyan,cellular,Pooled Split
220,AVG,2,0.554014,0.466393,0.670008,0.468630,0.499881,0.719181,0.740259,0.688316,RASH_HUMAN_Kuriyan,cellular,Pooled Split
221,AVG,3,0.536357,0.471513,0.684369,0.560020,0.481769,0.649607,0.732811,0.727770,RASH_HUMAN_Kuriyan,cellular,Pooled Split

In [7]:
AVG_grouped = AVG.groupby(['Dataset', 'Source', 'Model', 'Split',], as_index=False)['R2_score_test'].mean()
AVG_grouped

,Dataset,Source,Model,Split,R2_score_test
0,AMIE_PSEAE_Whitehead,cellular,AVG,Pooled Split,0.405258
1,B3VI55_LIPSTSTABLE,cellular,AVG,Pooled Split,0.254094
2,B3VI55_LIPST_Whitehead2015,cellular,AVG,Pooled Split,0.162333
3,BG_STRSQ_hmmerbit,cellular,AVG,Pooled Split,0.102000
4,BLAT_ECOLX_Ostermeier2014,cellular,AVG,Pooled Split,0.455095
...,...,...,...,...,...
69,TPK1_HUMAN_Roth2017,cellular,AVG,Pooled Split,-0.028949
70,TPMT_HUMAN_Fowler2018,cellular,AVG,Pooled Split,0.229463
71,UBC9_HUMAN_Roth2017,cellular,AVG,Pooled Split,0.329162
72,UBE4B_MOUSE_Klevit2013_singles,cellular,AVG,Pooled Split,0.115625
73,YAP1_HUMAN_Fields2012_singles,cellular,AVG,Pooled Split,0.357715

In [8]:
all_models_lasso = pd.read_csv("../experiments/compiled_results/res_lassoCV_all_models.csv")
esm2_pooled = all_models_lasso.query('Model == "ESM-2 650M" & Split == "Pooled Split"')
esm2_pooled_grouped = esm2_pooled.groupby(['Dataset', 'Source', 'Model', 'Split',], as_index=False)['R2_score_test'].mean()
esm2_pooled_grouped

,Dataset,Source,Model,Split,R2_score_test
0,AMIE_PSEAE_Whitehead,cellular,ESM-2 650M,Pooled Split,0.486188
1,B3VI55_LIPSTSTABLE,cellular,ESM-2 650M,Pooled Split,0.468531
2,B3VI55_LIPST_Whitehead2015,cellular,ESM-2 650M,Pooled Split,0.256701
3,BG_STRSQ_hmmerbit,cellular,ESM-2 650M,Pooled Split,0.427510
4,BLAT_ECOLX_Ostermeier2014,cellular,ESM-2 650M,Pooled Split,0.666155
...,...,...,...,...,...
69,TPK1_HUMAN_Roth2017,cellular,ESM-2 650M,Pooled Split,0.129374
70,TPMT_HUMAN_Fowler2018,cellular,ESM-2 650M,Pooled Split,0.458016
71,UBC9_HUMAN_Roth2017,cellular,ESM-2 650M,Pooled Split,0.403438
72,UBE4B_MOUSE_Klevit2013_singles,cellular,ESM-2 650M,Pooled Split,0.240093
73,YAP1_HUMAN_Fields2012_singles,cellular,ESM-2 650M,Pooled Split,0.453924

In [9]:
res = pd.concat([esm2_pooled_grouped, AVG_grouped], axis=0)
res

,Dataset,Source,Model,Split,R2_score_test
0,AMIE_PSEAE_Whitehead,cellular,ESM-2 650M,Pooled Split,0.486188
1,B3VI55_LIPSTSTABLE,cellular,ESM-2 650M,Pooled Split,0.468531
2,B3VI55_LIPST_Whitehead2015,cellular,ESM-2 650M,Pooled Split,0.256701
3,BG_STRSQ_hmmerbit,cellular,ESM-2 650M,Pooled Split,0.427510
4,BLAT_ECOLX_Ostermeier2014,cellular,ESM-2 650M,Pooled Split,0.666155
...,...,...,...,...,...
69,TPK1_HUMAN_Roth2017,cellular,AVG,Pooled Split,-0.028949
70,TPMT_HUMAN_Fowler2018,cellular,AVG,Pooled Split,0.229463
71,UBC9_HUMAN_Roth2017,cellular,AVG,Pooled Split,0.329162
72,UBE4B_MOUSE_Klevit2013_singles,cellular,AVG,Pooled Split,0.115625
73,YAP1_HUMAN_Fields2012_singles,cellular,AVG,Pooled Split,0.357715

In [10]:
res_pivot = pd.pivot_table(res, index=['Dataset','Source', 'Split'], columns= 'Model', values='R2_score_test').reset_index()
res_pivot = res_pivot.rename(columns={"AVG":"R2_AVG", "ESM-2 650M":"R2_ESM2_650M"})
res_pivot

Model,Dataset,Source,Split,R2_AVG,R2_ESM2_650M
0,AMIE_PSEAE_Whitehead,cellular,Pooled Split,0.405258,0.486188
1,B3VI55_LIPSTSTABLE,cellular,Pooled Split,0.254094,0.468531
2,B3VI55_LIPST_Whitehead2015,cellular,Pooled Split,0.162333,0.256701
3,BG_STRSQ_hmmerbit,cellular,Pooled Split,0.102000,0.427510
4,BLAT_ECOLX_Ostermeier2014,cellular,Pooled Split,0.455095,0.666155
...,...,...,...,...,...
69,TPK1_HUMAN_Roth2017,cellular,Pooled Split,-0.028949,0.129374
70,TPMT_HUMAN_Fowler2018,cellular,Pooled Split,0.229463,0.458016
71,UBC9_HUMAN_Roth2017,cellular,Pooled Split,0.329162,0.403438
72,UBE4B_MOUSE_Klevit2013_singles,cellular,Pooled Split,0.115625,0.240093
73,YAP1_HUMAN_Fields2012_singles,cellular,Pooled Split,0.357715,0.453924

In [ ]:
#res_pivot.to_csv("../experiments/compiled_results/res_lassoCV_x_AVG.csv")